# Generated by Django 6.0.3 on 2026-03-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_application_resume_alter_application_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='seeker',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='employer',
            new_name='company',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='Full-time', max_length=100),
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
