# Generated by Django 6.0.3 on 2026-03-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_seeker_application_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
